import { db, questionsTable } from "@workspace/db";

const QUESTIONS = [
  // Language English
  { subject: "language_english", topic: "vocabulary_and_analogy", text: "Choose the word that is most nearly the same in meaning as the given word:\n\nABERRANT", choices: [{ id: "A", text: "normal" }, { id: "B", text: "abnormal" }, { id: "C", text: "consistent" }, { id: "D", text: "predictable" }], correctAnswer: "B", explanation: "Aberrant means departing from an accepted standard; abnormal or unusual." },
  { subject: "language_english", topic: "vocabulary_and_analogy", text: "Choose the word that is most nearly the opposite in meaning to the given word:\n\nEPHEMERAL", choices: [{ id: "A", text: "permanent" }, { id: "B", text: "fleeting" }, { id: "C", text: "transient" }, { id: "D", text: "momentary" }], correctAnswer: "A", explanation: "Ephemeral means lasting for a very short time. The opposite is permanent." },
  { subject: "language_english", topic: "vocabulary_and_analogy", text: "Select the pair that best expresses a relationship similar to that of the original pair:\n\nDOG : KENNEL ::", choices: [{ id: "A", text: "bird : aviary" }, { id: "B", text: "fish : ocean" }, { id: "C", text: "lion : den" }, { id: "D", text: "horse : stable" }], correctAnswer: "D", explanation: "A kennel is a dog's dwelling. A stable is a horse's dwelling." },
  { subject: "language_english", topic: "sentence_completion", text: "INSTRUCTION: Choose the best word to complete the sentence.\n\nThe students were _____ by the complexity of the calculus problem, so they asked the professor for a step-by-step explanation.", choices: [{ id: "A", text: "enthralled" }, { id: "B", text: "baffled" }, { id: "C", text: "emboldened" }, { id: "D", text: "enamored" }], correctAnswer: "B", explanation: "Baffled means confused, which fits the context of needing an explanation." },
  { subject: "language_english", topic: "sentence_completion", text: "INSTRUCTION: Choose the best word to complete the sentence.\n\nDespite the harsh criticism, the artist remained _____ and continued to pursue his unconventional style.", choices: [{ id: "A", text: "obsequious" }, { id: "B", text: "resolute" }, { id: "C", text: "fickle" }, { id: "D", text: "apologetic" }], correctAnswer: "B", explanation: "Resolute means determined, which fits the context of continuing despite criticism." },
  { subject: "language_english", topic: "sentence_completion", text: "INSTRUCTION: Choose the best word to complete the sentence.\n\nThe diplomat's remarks were deliberately _____ so as not to offend either party during the negotiations.", choices: [{ id: "A", text: "incisive" }, { id: "B", text: "trenchant" }, { id: "C", text: "equivocal" }, { id: "D", text: "unambiguous" }], correctAnswer: "C", explanation: "Equivocal means deliberately ambiguous, which fits a diplomatic context." },
  { subject: "language_english", topic: "identifying_error", text: "INSTRUCTION: Identify the error in the sentence.\n\nShe [don't] know the answer to the question, so she asked the teacher for help.", choices: [{ id: "A", text: "don't" }, { id: "B", text: "know" }, { id: "C", text: "to the question" }, { id: "D", text: "asked" }], correctAnswer: "A", explanation: "The subject 'She' is third person singular, so the correct verb form is 'doesn't' not 'don't'." },
  { subject: "language_english", topic: "identifying_error", text: "INSTRUCTION: Identify the error in the sentence.\n\nThe students, along with their teacher, [was] preparing for the upcoming examination.", choices: [{ id: "A", text: "The students" }, { id: "B", text: "along with their teacher" }, { id: "C", text: "was" }, { id: "D", text: "preparing for the upcoming examination" }], correctAnswer: "C", explanation: "The subject is 'The students' (plural), so the verb should be 'were' not 'was'." },
  { subject: "language_english", topic: "identifying_error", text: "INSTRUCTION: Identify the error in the sentence.\n\nThe data [was] collected by the researchers last month.", choices: [{ id: "A", text: "The data" }, { id: "B", text: "was" }, { id: "C", text: "collected" }, { id: "D", text: "last month" }], correctAnswer: "B", explanation: "'Data' is technically a plural noun from Latin, so 'were' is preferred, though 'was' is commonly accepted in modern usage." },
  { subject: "language_english", topic: "idiomatic_expression", text: "INSTRUCTION: Choose the correct idiomatic expression to complete the sentence.\n\nAfter losing three consecutive games, the team finally decided to _____ and focus on their weaknesses.", choices: [{ id: "A", text: "go back to the drawing board" }, { id: "B", text: "cut corners" }, { id: "C", text: "hit the sack" }, { id: "D", text: "break the ice" }], correctAnswer: "A", explanation: "'Go back to the drawing board' means to start over with a new plan or approach." },
  { subject: "language_english", topic: "idiomatic_expression", text: "INSTRUCTION: Choose the correct meaning of the idiom.\n\n'Burn the midnight oil' means:", choices: [{ id: "A", text: "To waste time" }, { id: "B", text: "To work late into the night" }, { id: "C", text: "To start a fire" }, { id: "D", text: "To finish quickly" }], correctAnswer: "B", explanation: "'Burn the midnight oil' means to work late into the night, especially studying or working hard." },
  { subject: "language_english", topic: "related_pair_of_words", text: "INSTRUCTION: Choose the pair that best expresses a relationship similar to that of the original pair.\n\nTEACHER : STUDENT ::", choices: [{ id: "A", text: "doctor : patient" }, { id: "B", text: "driver : car" }, { id: "C", text: "chef : restaurant" }, { id: "D", text: "writer : book" }], correctAnswer: "A", explanation: "A teacher instructs a student. A doctor treats a patient. Both are professional-client relationships." },
  { subject: "language_english", topic: "related_pair_of_words", text: "INSTRUCTION: Choose the pair that best expresses a relationship similar to that of the original pair.\n\nBROOM : SWEEP ::", choices: [{ id: "A", text: "knife : cut" }, { id: "B", text: "pen : write" }, { id: "C", text: "shovel : dig" }, { id: "D", text: "pencil : erase" }], correctAnswer: "C", explanation: "A broom is used to sweep. A shovel is used to dig. Both are tools and their primary actions." },
  { subject: "language_english", topic: "correct_word_usage", text: "INSTRUCTION: Choose the correct word.\n\nThe _____ of the evidence was undeniable.", choices: [{ id: "A", text: "credibility" }, { id: "B", text: "credulity" }, { id: "C", text: "credible" }, { id: "D", text: "credulous" }], correctAnswer: "A", explanation: "Credibility means the quality of being believable or trustworthy. Credulity means a tendency to believe things too easily." },
  { subject: "language_english", topic: "correct_word_usage", text: "INSTRUCTION: Choose the correct word.\n\nHe was _____ by the magician's tricks.", choices: [{ id: "A", text: "eluded" }, { id: "B", text: "alluded" }, { id: "C", text: "deluded" }, { id: "D", text: "precluded" }], correctAnswer: "C", explanation: "Deluded means deceived or misled. Eluded means escaped, alluded means referred to indirectly." },
  { subject: "language_english", topic: "sentence_sequencing", text: "INSTRUCTION: Arrange the sentences in the most logical order.\n\n1. The Philippines declared independence on June 12, 1898.\n2. Spain had colonized the Philippines for over 300 years.\n3. General Emilio Aguinaldo proclaimed the independence.\n4. The Spanish-American War led to the end of Spanish rule.\n\nWhat is the correct sequence?", choices: [{ id: "A", text: "2-4-3-1" }, { id: "B", text: "2-4-1-3" }, { id: "C", text: "4-2-1-3" }, { id: "D", text: "4-1-2-3" }], correctAnswer: "B", explanation: "First, Spain colonized the Philippines (2). Then the Spanish-American War ended Spanish rule (4). Then independence was declared (1), and Aguinaldo proclaimed it (3)." },
  { subject: "language_english", topic: "sentence_sequencing", text: "INSTRUCTION: Arrange the sentences in the most logical order.\n\n1. Plants absorb carbon dioxide from the atmosphere.\n2. Through photosynthesis, they convert it into glucose.\n3. The glucose provides energy for the plant's growth.\n4. Oxygen is released as a byproduct.\n\nWhat is the correct sequence?", choices: [{ id: "A", text: "1-2-3-4" }, { id: "B", text: "1-2-4-3" }, { id: "C", text: "3-1-2-4" }, { id: "D", text: "4-1-2-3" }], correctAnswer: "B", explanation: "Plants absorb CO2 (1), convert it to glucose via photosynthesis (2), release oxygen as byproduct (4), and glucose provides energy (3)." },

  // Language Filipino
  { subject: "language_filipino", topic: "bokabularyo_at_paghahalintulad", text: "PANUTO: Piliin ang salitang kasingkahulugan ng salitang may salungguhit.\n\nAng mga _____ ng kanyang mga salita ay hindi maipagkakaila.", choices: [{ id: "A", text: "kasinungalingan" }, { id: "B", text: "katotohanan" }, { id: "C", text: "kawalang-hiyaan" }, { id: "D", text: "kagandahan" }], correctAnswer: "B", explanation: "Ang 'katotohanan' ay ang kasingkahulugan ng 'katotohanan' — ang ibig sabihin ng 'katotohanan' ay ang mga salitang hindi maipagkakaila." },
  { subject: "language_filipino", topic: "bokabularyo_at_paghahalintulad", text: "PANUTO: Piliin ang salitang kasingkahulugan.\n\nGALIT", choices: [{ id: "A", text: "sayang" }, { id: "B", text: "puot" }, { id: "C", text: "saya" }, { id: "D", text: "tawa" }], correctAnswer: "B", explanation: "Ang 'puot' ay ang kasingkahulugan ng 'galit' sa Filipino." },
  { subject: "language_filipino", topic: "pagkakasunod_ng_pangungusap", text: "PANUTO: Ayusin ang mga pangungusap ayon sa tamang pagkakasunod-sunod.\n\n1. Ang mga sinaunang Pilipino ay naninirahan sa tabing-dagat.\n2. Sila ay nangangaso at nangangisda para sa kanilang pagkain.\n3. Ang mga ito ay bahagi ng kanilang pang-araw-araw na gawain.\n4. Sa paglipas ng panahon, lumaganap ang agrikultura.\n\nAno ang tamang pagkakasunod?", choices: [{ id: "A", text: "1-2-3-4" }, { id: "B", text: "2-1-3-4" }, { id: "C", text: "1-3-2-4" }, { id: "D", text: "4-1-2-3" }], correctAnswer: "A", explanation: "Ang mga sinaunang Pilipino ay naninirahan sa tabing-dagat (1), nangangaso at nangangisda (2), ito ay bahagi ng pang-araw-araw na gawain (3), at lumaganap ang agrikultura (4)." },
  { subject: "language_filipino", topic: "pagkumpleto_ng_pangungusap", text: "PANUTO: Piliin ang salitang pinaka-angkop upang makumpleto ang pangungusap.\n\nAng mga mag-aaral ay _____ sa pag-aaral dahil malapit na ang kanilang pagsusulit.", choices: [{ id: "A", text: "masigasig" }, { id: "B", text: "tamad" }, { id: "C", text: "tuyo" }, { id: "D", text: "bagal" }], correctAnswer: "A", explanation: "Ang 'masigasig' ay ang tamang salitang nagpapahiwatig ng sipag at dedikasyon sa pag-aaral." },
  { subject: "language_filipino", topic: "pagkilala_ng_mali", text: "PANUTO: Kilalanin ang mali sa pangungusap.\n\nAng mga estudyante [ay] nag-aaral ng mabuti para sa kanilang [mga] pagsusulit [dahil] nais nilang [magkaroón] ng magandang marka.", choices: [{ id: "A", text: "ay" }, { id: "B", text: "mga" }, { id: "C", text: "dahil" }, { id: "D", text: "magkaroón" }], correctAnswer: "D", explanation: "Ang tamang salita ay 'magkaroon' hindi 'magkaroón'." },
  { subject: "language_filipino", topic: "idyomatikong_ekspresyon", text: "PANUTO: Piliin ang kahulugan ng idyoma.\n\n'Nagsusunog ng kilay' ay nangangahulugang:", choices: [{ id: "A", text: "Nag-aaral ng mabuti" }, { id: "B", text: "Nagagalit" }, { id: "C", text: "Nagtatrabaho" }, { id: "D", text: "Nag-iiyakan" }], correctAnswer: "A", explanation: "Ang 'nagsusunog ng kilay' ay idyoma na nangangahulugang nag-aaral ng mabuti o nagrereview nang husto." },
  { subject: "language_filipino", topic: "idyomatikong_ekspresyon", text: "PANUTO: Piliin ang kahulugan ng idyoma.\n\n'Nagtataingang kawali' ay nangangahulugang:", choices: [{ id: "A", text: "Nakikinig nang mabuti" }, { id: "B", text: "Hindi nakikinig" }, { id: "C", text: "Nagtatrabaho sa kusina" }, { id: "D", text: "Nagluluto ng kawali" }], correctAnswer: "B", explanation: "Ang 'nagtataingang kawali' ay idyoma na nangangahulugang hindi nakikinig o bingi sa sinasabi." },
  { subject: "language_filipino", topic: "magkaugnay_na_pares", text: "PANUTO: Piliin ang pares na may magkaugnay na relasyon.\n\nGURU : MAG-AARAL ::", choices: [{ id: "A", text: "doktor : pasyente" }, { id: "B", text: "manlalaro : bola" }, { id: "C", text: "magsasaka : bukid" }, { id: "D", text: "mangangaso : baril" }], correctAnswer: "A", explanation: "Ang guru ay nagtuturo sa mag-aaral. Ang doktor ay nagpapagaling sa pasyente." },
  { subject: "language_filipino", topic: "wastong_gamit_ng_salita", text: "PANUTO: Piliin ang tamang salita.\n\nAng _____ ng ebidensya ay hindi maipagkakaila.", choices: [{ id: "A", text: "kredibilidad" }, { id: "B", text: "kredulidad" }, { id: "C", text: "kredito" }, { id: "D", text: "kredensyal" }], correctAnswer: "A", explanation: "Ang 'kredibilidad' ay ang katangian ng pagiging mapagkakatiwalaan. Ang 'kredulidad' ay ang pagiging mapagpaniwala." },
  { subject: "language_filipino", topic: "wastong_gamit_ng_salita", text: "PANUTO: Piliin ang tamang salita.\n\nSiya ay _____ ng mga magagandang tanawin sa probinsya.", choices: [{ id: "A", text: "nabighani" }, { id: "B", text: "nabigla" }, { id: "C", text: "nabigong" }, { id: "D", text: "nabihag" }], correctAnswer: "A", explanation: "Ang 'nabighani' ay ang pagkakaroon ng labis na paghanga." },

  // Math
  { subject: "math", topic: "algebra_numbers_integers", text: "INSTRUCTION: Solve the problem.\n\nWhat is the sum of all integers from 1 to 100?", choices: [{ id: "A", text: "4950" }, { id: "B", text: "5000" }, { id: "C", text: "5050" }, { id: "D", text: "5100" }], correctAnswer: "C", explanation: "Using the formula n(n+1)/2: 100 × 101 / 2 = 5050." },
  { subject: "math", topic: "algebra_numbers_integers", text: "INSTRUCTION: Solve the problem.\n\nIf 3x - 7 = 20, what is the value of x?", choices: [{ id: "A", text: "7" }, { id: "B", text: "8" }, { id: "C", text: "9" }, { id: "D", text: "10" }], correctAnswer: "C", explanation: "3x - 7 = 20 → 3x = 27 → x = 9." },
  { subject: "math", topic: "decimals_fractions_percent", text: "INSTRUCTION: Solve the problem.\n\nWhat is 25% of 480?", choices: [{ id: "A", text: "100" }, { id: "B", text: "120" }, { id: "C", text: "140" }, { id: "D", text: "160" }], correctAnswer: "B", explanation: "25% of 480 = 0.25 × 480 = 120." },
  { subject: "math", topic: "decimals_fractions_percent", text: "INSTRUCTION: Solve the problem.\n\nIf a shirt costs Php 800 and is on sale for 15% off, what is the sale price?", choices: [{ id: "A", text: "Php 660" }, { id: "B", text: "Php 680" }, { id: "C", text: "Php 700" }, { id: "D", text: "Php 720" }], correctAnswer: "B", explanation: "15% of 800 = 120. 800 - 120 = 680." },
  { subject: "math", topic: "ratio_proportion", text: "INSTRUCTION: Solve the problem.\n\nThe ratio of boys to girls in a class is 3:4. If there are 21 boys, how many girls are there?", choices: [{ id: "A", text: "24" }, { id: "B", text: "26" }, { id: "C", text: "28" }, { id: "D", text: "30" }], correctAnswer: "C", explanation: "3/4 = 21/x → 3x = 84 → x = 28." },
  { subject: "math", topic: "ratio_proportion", text: "INSTRUCTION: Solve the problem.\n\nA map has a scale of 1:50000. If two cities are 3 cm apart on the map, what is the actual distance in kilometers?", choices: [{ id: "A", text: "1.5 km" }, { id: "B", text: "2 km" }, { id: "C", text: "2.5 km" }, { id: "D", text: "3 km" }], correctAnswer: "A", explanation: "3 cm × 50000 = 150000 cm = 1500 m = 1.5 km." },
  { subject: "math", topic: "variations", text: "INSTRUCTION: Solve the problem.\n\nIf y varies directly as x and y = 12 when x = 3, what is the value of y when x = 5?", choices: [{ id: "A", text: "15" }, { id: "B", text: "18" }, { id: "C", text: "20" }, { id: "D", text: "24" }], correctAnswer: "C", explanation: "y = kx. 12 = k(3) → k = 4. y = 4(5) = 20." },
  { subject: "math", topic: "variations", text: "INSTRUCTION: Solve the problem.\n\nIf y varies inversely as x and y = 6 when x = 4, what is the value of y when x = 3?", choices: [{ id: "A", text: "6" }, { id: "B", text: "8" }, { id: "C", text: "12" }, { id: "D", text: "9" }], correctAnswer: "B", explanation: "y = k/x. 6 = k/4 → k = 24. y = 24/3 = 8." },
  { subject: "math", topic: "statistics", text: "INSTRUCTION: Solve the problem.\n\nWhat is the mean of the following numbers: 12, 15, 18, 21, 24?", choices: [{ id: "A", text: "15" }, { id: "B", text: "18" }, { id: "C", text: "20" }, { id: "D", text: "21" }], correctAnswer: "B", explanation: "Mean = (12+15+18+21+24)/5 = 90/5 = 18." },
  { subject: "math", topic: "statistics", text: "INSTRUCTION: Solve the problem.\n\nWhat is the median of the following numbers: 7, 3, 9, 12, 5, 8, 10?", choices: [{ id: "A", text: "7" }, { id: "B", text: "8" }, { id: "C", text: "9" }, { id: "D", text: "10" }], correctAnswer: "B", explanation: "Ordered: 3, 5, 7, 8, 9, 10, 12. Median (middle value) = 8." },
  { subject: "math", topic: "number_series_progressions", text: "INSTRUCTION: Find the next number in the sequence.\n\n2, 6, 12, 20, 30, ___", choices: [{ id: "A", text: "38" }, { id: "B", text: "40" }, { id: "C", text: "42" }, { id: "D", text: "44" }], correctAnswer: "C", explanation: "Pattern: n(n+1) where n=1,2,3,4,5,6... So 6×7 = 42." },
  { subject: "math", topic: "number_series_progressions", text: "INSTRUCTION: Find the next number in the sequence.\n\n1, 1, 2, 3, 5, 8, 13, ___", choices: [{ id: "A", text: "18" }, { id: "B", text: "19" }, { id: "C", text: "20" }, { id: "D", text: "21" }], correctAnswer: "D", explanation: "Fibonacci sequence: each number is the sum of the two preceding numbers. 8 + 13 = 21." },
  { subject: "math", topic: "algebra_polynomials", text: "INSTRUCTION: Solve the problem.\n\nWhat is the value of x in the equation x² - 5x + 6 = 0?", choices: [{ id: "A", text: "2 and 3" }, { id: "B", text: "1 and 6" }, { id: "C", text: "-2 and -3" }, { id: "D", text: "-1 and -6" }], correctAnswer: "A", explanation: "Factoring: (x-2)(x-3) = 0 → x = 2 or x = 3." },
  { subject: "math", topic: "plane_geometry", text: "INSTRUCTION: Solve the problem.\n\nWhat is the area of a triangle with base 12 cm and height 8 cm?", choices: [{ id: "A", text: "40 cm²" }, { id: "B", text: "48 cm²" }, { id: "C", text: "56 cm²" }, { id: "D", text: "96 cm²" }], correctAnswer: "B", explanation: "Area = (base × height) / 2 = (12 × 8) / 2 = 48 cm²." },
  { subject: "math", topic: "plane_geometry", text: "INSTRUCTION: Solve the problem.\n\nWhat is the circumference of a circle with radius 7 cm? (Use π = 22/7)", choices: [{ id: "A", text: "22 cm" }, { id: "B", text: "33 cm" }, { id: "C", text: "44 cm" }, { id: "D", text: "49 cm" }], correctAnswer: "C", explanation: "Circumference = 2πr = 2 × (22/7) × 7 = 44 cm." },
  { subject: "math", topic: "analytic_geometry", text: "INSTRUCTION: Solve the problem.\n\nWhat is the slope of the line passing through points (2, 3) and (4, 7)?", choices: [{ id: "A", text: "1" }, { id: "B", text: "2" }, { id: "C", text: "3" }, { id: "D", text: "4" }], correctAnswer: "B", explanation: "Slope = (y2 - y1) / (x2 - x1) = (7-3)/(4-2) = 4/2 = 2." },
  { subject: "math", topic: "trigonometry", text: "INSTRUCTION: Solve the problem.\n\nIn a right triangle, if sin A = 3/5, what is cos A?", choices: [{ id: "A", text: "3/5" }, { id: "B", text: "4/5" }, { id: "C", text: "5/4" }, { id: "D", text: "5/3" }], correctAnswer: "B", explanation: "Using sin²A + cos²A = 1: cos A = √(1 - 9/25) = √(16/25) = 4/5." },
  { subject: "math", topic: "word_problems", text: "INSTRUCTION: Solve the word problem.\n\nAna is 5 years older than Ben. In 3 years, the sum of their ages will be 37. How old is Ana now?", choices: [{ id: "A", text: "14" }, { id: "B", text: "16" }, { id: "C", text: "18" }, { id: "D", text: "19" }], correctAnswer: "C", explanation: "Let Ben = x, Ana = x+5. In 3 years: (x+3)+(x+8)=37 → 2x+11=37 → x=13. Ana is 13+5=18." },
  { subject: "math", topic: "word_problems", text: "INSTRUCTION: Solve the word problem.\n\nA farmer has chickens and pigs. There are 40 heads and 112 legs in total. How many chickens are there?", choices: [{ id: "A", text: "20" }, { id: "B", text: "22" }, { id: "C", text: "24" }, { id: "D", text: "26" }], correctAnswer: "C", explanation: "Let chickens = c, pigs = p. c + p = 40, 2c + 4p = 112. Solving: c = 24, p = 16." },
  { subject: "math", topic: "word_problems", text: "INSTRUCTION: Solve the word problem.\n\nA train travels 240 km in 4 hours. What is its average speed in km/h?", choices: [{ id: "A", text: "50" }, { id: "B", text: "60" }, { id: "C", text: "70" }, { id: "D", text: "80" }], correctAnswer: "B", explanation: "Speed = Distance / Time = 240 km / 4 h = 60 km/h." },

  // Science
  { subject: "science", topic: "chem_atomic_structure", text: "INSTRUCTION: Choose the best answer.\n\nWhich subatomic particle has a positive charge?", choices: [{ id: "A", text: "Electron" }, { id: "B", text: "Neutron" }, { id: "C", text: "Proton" }, { id: "D", text: "Positron" }], correctAnswer: "C", explanation: "Protons carry a positive charge (+1). Electrons are negative, neutrons are neutral." },
  { subject: "science", topic: "chem_matter", text: "INSTRUCTION: Choose the best answer.\n\nWhich of the following is a chemical change?", choices: [{ id: "A", text: "Melting ice" }, { id: "B", text: "Dissolving salt in water" }, { id: "C", text: "Burning wood" }, { id: "D", text: "Crushing a can" }], correctAnswer: "C", explanation: "Burning wood is a chemical change because new substances are formed (ash, smoke, gases)." },
  { subject: "science", topic: "chem_bonding", text: "INSTRUCTION: Choose the best answer.\n\nWhat type of bond forms between sodium and chlorine in NaCl?", choices: [{ id: "A", text: "Covalent bond" }, { id: "B", text: "Ionic bond" }, { id: "C", text: "Metallic bond" }, { id: "D", text: "Hydrogen bond" }], correctAnswer: "B", explanation: "NaCl is an ionic compound formed by the transfer of electrons from sodium to chlorine." },
  { subject: "science", topic: "chem_stoichiometry", text: "INSTRUCTION: Solve the problem.\n\nHow many moles of oxygen atoms are in 2 moles of H₂O?", choices: [{ id: "A", text: "1 mole" }, { id: "B", text: "2 moles" }, { id: "C", text: "3 moles" }, { id: "D", text: "4 moles" }], correctAnswer: "B", explanation: "Each H₂O molecule contains 1 oxygen atom. So 2 moles of H₂O contain 2 moles of O atoms." },
  { subject: "science", topic: "gen_force", text: "INSTRUCTION: Choose the best answer.\n\nAccording to Newton's Second Law, if the mass of an object is doubled while the net force remains constant, the acceleration will:", choices: [{ id: "A", text: "double" }, { id: "B", text: "be halved" }, { id: "C", text: "remain the same" }, { id: "D", text: "quadruple" }], correctAnswer: "B", explanation: "F = ma. If F is constant and m doubles, a must be halved to maintain the equation." },
  { subject: "science", topic: "gen_force", text: "INSTRUCTION: Solve the problem.\n\nA 10 kg object is pushed with a net force of 50 N. What is its acceleration?", choices: [{ id: "A", text: "2 m/s²" }, { id: "B", text: "5 m/s²" }, { id: "C", text: "10 m/s²" }, { id: "D", text: "500 m/s²" }], correctAnswer: "B", explanation: "a = F/m = 50 N / 10 kg = 5 m/s²." },
  { subject: "science", topic: "gen_weather_climate", text: "INSTRUCTION: Choose the best answer.\n\nWhich layer of the atmosphere contains the ozone layer?", choices: [{ id: "A", text: "Troposphere" }, { id: "B", text: "Stratosphere" }, { id: "C", text: "Mesosphere" }, { id: "D", text: "Thermosphere" }], correctAnswer: "B", explanation: "The ozone layer is located in the stratosphere, approximately 10-50 km above Earth's surface." },
  { subject: "science", topic: "gen_layers_earth", text: "INSTRUCTION: Choose the best answer.\n\nWhich is the outermost layer of the Earth?", choices: [{ id: "A", text: "Mantle" }, { id: "B", text: "Inner core" }, { id: "C", text: "Outer core" }, { id: "D", text: "Crust" }], correctAnswer: "D", explanation: "The crust is the outermost layer of the Earth, followed by the mantle, outer core, and inner core." },
  { subject: "science", topic: "bio_genetics", text: "INSTRUCTION: Choose the best answer.\n\nWhat is the basic unit of heredity?", choices: [{ id: "A", text: "Chromosome" }, { id: "B", text: "Gene" }, { id: "C", text: "DNA" }, { id: "D", text: "Nucleus" }], correctAnswer: "B", explanation: "A gene is the basic unit of heredity, made of DNA, that carries the instructions for a specific trait." },
  { subject: "science", topic: "bio_genetics", text: "INSTRUCTION: Choose the best answer.\n\nIn a DNA molecule, which nitrogenous base pairs with adenine?", choices: [{ id: "A", text: "Cytosine" }, { id: "B", text: "Guanine" }, { id: "C", text: "Thymine" }, { id: "D", text: "Uracil" }], correctAnswer: "C", explanation: "In DNA, adenine (A) always pairs with thymine (T), and cytosine (C) pairs with guanine (G)." },
  { subject: "science", topic: "bio_plants", text: "INSTRUCTION: Choose the best answer.\n\nWhich organelle is responsible for photosynthesis in plant cells?", choices: [{ id: "A", text: "Mitochondria" }, { id: "B", text: "Chloroplast" }, { id: "C", text: "Nucleus" }, { id: "D", text: "Ribosome" }], correctAnswer: "B", explanation: "Chloroplasts contain chlorophyll and are the site of photosynthesis in plant cells." },
  { subject: "science", topic: "bio_evolution", text: "INSTRUCTION: Choose the best answer.\n\nWho proposed the theory of evolution by natural selection?", choices: [{ id: "A", text: "Gregor Mendel" }, { id: "B", text: "Charles Darwin" }, { id: "C", text: "Louis Pasteur" }, { id: "D", text: "Albert Einstein" }], correctAnswer: "B", explanation: "Charles Darwin proposed the theory of evolution by natural selection in his book 'On the Origin of Species' (1859)." },
  { subject: "science", topic: "phys_newton_laws", text: "INSTRUCTION: Choose the best answer.\n\nNewton's Third Law states that for every action, there is:", choices: [{ id: "A", text: "an equal and opposite reaction" }, { id: "B", text: "a proportional reaction" }, { id: "C", text: "no reaction" }, { id: "D", text: "a delayed reaction" }], correctAnswer: "A", explanation: "Newton's Third Law: For every action, there is an equal and opposite reaction." },
  { subject: "science", topic: "phys_energy", text: "INSTRUCTION: Solve the problem.\n\nWhat is the kinetic energy of a 2 kg object moving at 5 m/s?", choices: [{ id: "A", text: "10 J" }, { id: "B", text: "25 J" }, { id: "C", text: "50 J" }, { id: "D", text: "100 J" }], correctAnswer: "B", explanation: "KE = ½mv² = ½(2)(5)² = ½(2)(25) = 25 J." },
  { subject: "science", topic: "phys_momentum", text: "INSTRUCTION: Solve the problem.\n\nWhat is the momentum of a 5 kg ball moving at 4 m/s?", choices: [{ id: "A", text: "9 kg·m/s" }, { id: "B", text: "10 kg·m/s" }, { id: "C", text: "20 kg·m/s" }, { id: "D", text: "25 kg·m/s" }], correctAnswer: "C", explanation: "Momentum p = mv = 5 kg × 4 m/s = 20 kg·m/s." },

  // Reading English
  { subject: "reading_english", topic: "passage", text: "PASSAGE:\nThe Philippine eagle, one of the world's largest and most powerful birds, faces extinction due to habitat loss. Its forest home in Mindanao continues to shrink as logging and farming expand. Conservation efforts are underway, but the future of this majestic bird remains uncertain.\n\nINSTRUCTION: Read the passage and answer the question.\n\nQUESTION: What is the main threat to the Philippine eagle according to the passage?", choices: [{ id: "A", text: "Hunting by local farmers" }, { id: "B", text: "Habitat loss due to logging and farming" }, { id: "C", text: "Competition with other eagle species" }, { id: "D", text: "Climate change affecting food supply" }], correctAnswer: "B", explanation: "The passage explicitly states that its forest home continues to shrink 'as logging and farming expand,' making habitat loss the main threat." },
  { subject: "reading_english", topic: "passage", text: "PASSAGE:\nThe Philippine eagle, one of the world's largest and most powerful birds, faces extinction due to habitat loss. Its forest home in Mindanao continues to shrink as logging and farming expand. Conservation efforts are underway, but the future of this majestic bird remains uncertain.\n\nINSTRUCTION: Read the passage and answer the question.\n\nQUESTION: What is the tone of the passage?", choices: [{ id: "A", text: "Optimistic" }, { id: "B", text: "Pessimistic" }, { id: "C", text: "Neutral and concerned" }, { id: "D", text: "Humorous" }], correctAnswer: "C", explanation: "The passage presents factual information about the eagle's situation while noting conservation efforts, with a tone that is concerned but not overly negative." },
  { subject: "reading_english", topic: "passage", text: "PASSAGE:\nMaria grew up in a small village where education was scarce. Despite her family's financial struggles, she walked two hours every day to attend the nearest school. Her determination paid off when she became the first person in her village to graduate from university.\n\nINSTRUCTION: Read the passage and answer the question.\n\nQUESTION: What is the main idea of the passage?", choices: [{ id: "A", text: "Walking to school is good exercise" }, { id: "B", text: "Maria's perseverance led to her success despite obstacles" }, { id: "C", text: "Villages need more schools" }, { id: "D", text: "University is difficult to attend" }], correctAnswer: "B", explanation: "The passage emphasizes Maria's determination and hard work in overcoming obstacles, leading to her success." },
  { subject: "reading_english", topic: "passage", text: "PASSAGE:\nMaria grew up in a small village where education was scarce. Despite her family's financial struggles, she walked two hours every day to attend the nearest school. Her determination paid off when she became the first person in her village to graduate from university.\n\nINSTRUCTION: Read the passage and answer the question.\n\nQUESTION: What does the word 'perseverance' mean in the context of the passage?", choices: [{ id: "A", text: "Giving up easily" }, { id: "B", text: "Continuing despite difficulties" }, { id: "C", text: "Being wealthy" }, { id: "D", text: "Walking quickly" }], correctAnswer: "B", explanation: "Perseverance means continuing to work toward a goal despite difficulties, which Maria demonstrated by walking two hours daily." },
  { subject: "reading_english", topic: "passage", text: "PASSAGE:\nThe ancient Mayans developed a sophisticated calendar system that could predict astronomical events with remarkable accuracy. Their knowledge of mathematics and astronomy was far ahead of its time. Today, archaeologists continue to uncover new temples and inscriptions that reveal more about this advanced civilization.\n\nINSTRUCTION: Read the passage and answer the question.\n\nQUESTION: What can be inferred about the Mayan civilization?", choices: [{ id: "A", text: "They were primitive and uncivilized" }, { id: "B", text: "They had advanced knowledge of astronomy and mathematics" }, { id: "C", text: "They did not have a writing system" }, { id: "D", text: "They were only interested in agriculture" }], correctAnswer: "B", explanation: "The passage explicitly states that their knowledge of mathematics and astronomy was 'far ahead of its time' and that they had a sophisticated calendar system." },

  // Reading Filipino
  { subject: "reading_filipino", topic: "passage", text: "PASSAGE:\nAng mga mag-aaral sa maliit na barangay ay naglalakad ng dalawang oras araw-araw para makapasok sa pinakamalapit na paaralan. Sa kabila ng hirap, nananatili silang masigasig sa kanilang pag-aaral. Ang kanilang determinasyon ay nagbunga ng magagandang resulta, at marami sa kanila ang nakatapos ng kolehiyo.\n\nPANUTO: Basahin ang talata at sagutin ang tanong.\n\nTANONG: Ano ang pangunahing ideya ng talata?", choices: [{ id: "A", text: "Ang paglalakad ay mahirap" }, { id: "B", text: "Ang determinasyon sa pag-aaral ay nagbunga ng tagumpay" }, { id: "C", text: "Ang mga barangay ay maliliit" }, { id: "D", text: "Ang kolehiyo ay mahirap" }], correctAnswer: "B", explanation: "Ang talata ay naglalarawan ng pagtitiyaga ng mga mag-aaral at kung paano ito nagbunga ng tagumpay sa kanilang pag-aaral." },
  { subject: "reading_filipino", topic: "passage", text: "PASSAGE:\nAng mga mag-aaral sa maliit na barangay ay naglalakad ng dalawang oras araw-araw para makapasok sa pinakamalapit na paaralan. Sa kabila ng hirap, nananatili silang masigasig sa kanilang pag-aaral. Ang kanilang determinasyon ay nagbunga ng magagandang resulta, at marami sa kanila ang nakatapos ng kolehiyo.\n\nPANUTO: Basahin ang talata at sagutin ang tanong.\n\nTANONG: Ano ang ibig sabihin ng salitang 'masigasig' sa talata?", choices: [{ id: "A", text: "Tamad" }, { id: "B", text: "Masipag at determinado" }, { id: "C", text: "Malungkot" }, { id: "D", text: "Mabilis" }], correctAnswer: "B", explanation: "Ang 'masigasig' ay nangangahulugang masipag, determinado, at may malaking pagnanasa na magtagumpay." },
  { subject: "reading_filipino", topic: "passage", text: "PASSAGE:\nAng pulo ng Boracay ay isa sa pinakapopular na destinasyon sa Pilipinas. Kilala ito sa puting buhangin at malinaw na tubig. Taun-taon, daan-daang libong turista ang bumibisita dito. Ngunit, ang sobrang pagdagsa ng mga tao ay nagdulot ng polusyon at pagkasira ng kalikasan.\n\nPANUTO: Basahin ang talata at sagutin ang tanong.\n\nTANONG: Ano ang pangunahing suliranin sa Boracay ayon sa talata?", choices: [{ id: "A", text: "Kulang ang turista" }, { id: "B", text: "Polusyon at pagkasira ng kalikasan" }, { id: "C", text: "Mahal ang pamasahe" }, { id: "D", text: "Masamang panahon" }], correctAnswer: "B", explanation: "Ang talata ay nagsasabing ang sobrang pagdagsa ng mga tao ay nagdulot ng polusyon at pagkasira ng kalikasan sa Boracay." },
];

async function seed() {
  console.log(`Seeding ${QUESTIONS.length} questions...`);
  let count = 0;
  for (const q of QUESTIONS) {
    await db.insert(questionsTable).values({
      subject: q.subject,
      topic: q.topic,
      text: q.text,
      choices: q.choices as any,
      correctAnswer: q.correctAnswer,
      explanation: q.explanation,
    });
    count++;
  }
  console.log(`Seeded ${count} questions successfully.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
